<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NORIHUELA10" ignored="1" name="Test Lab Ej.1" tests="1" failures="1" timestamp="2020-09-21T19:24:03 ART" time="16.639" errors="0">
  <testcase name="registroUsuario" time="6.911" classname="pruebas.Laboratorio3_E1">
    <failure type="java.lang.AssertionError" message="expected [http://automationpractice.com/index.php?controller=authe] but found [http://automationpractice.com/index.php?controller=authentication]">
      <![CDATA[java.lang.AssertionError: expected [http://automationpractice.com/index.php?controller=authe] but found [http://automationpractice.com/index.php?controller=authentication]
at pruebas.Laboratorio3_E1.registroUsuario(Laboratorio3_E1.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- registroUsuario -->
  <testcase name="prueba" time="0.0" classname="pruebas.Laboratorio3_E1">
    <ignored/>
  </testcase> <!-- prueba -->
</testsuite> <!-- Test Lab Ej.1 -->
